cc_test(
  name = "interpret_test",
  srcs = ["interpret_test.c"],
  deps = [
    "@unity",
    "//main:interpret",
    "//main:node",
  ],
  timeout = "short"
)

cc_test(
  name = "regex_test",
  srcs = ["regex_test.c"],
  deps = [
    "@unity",    
    "//main:regex"
  ],
  timeout = "short"
)
